#!/bin/bash -e

# Newer OSX needs an include path for OpenSSL
if [[ `uname -s` == "Darwin" ]]; then
	export CGO_LDFLAGS="-L/usr/local/opt/openssl/lib"
fi

echo "Fetching Go dependencies and compiling code..."
go get -t ./...
