#!/bin/bash -e

MUPDF_VERSION="1.12.0"

if [[ ! -d mupdf ]]; then
	echo "Downloading muPDF..."
	git clone https://github.com/ArtifexSoftware/mupdf.git
	( cd mupdf && git checkout -q ${MUPDF_VERSION} )
	( cd mupdf/thirdparty && git submodule init && git submodule update --recursive )
fi

echo "Building muPDF..."
cd mupdf

make -j8 libs

# Newer OSX needs an include path for OpenSSL
if [[ `uname -s` == "Darwin" ]]; then
	export CGO_LDFLAGS="-L/usr/local/opt/openssl/lib"
fi

echo "Building Go application..."
cd -
go get ./...