linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - dogsled
    - godox
    - whitespace

linter-settings:
  goimports:
    local-prefixes: github.com/nitro/lazypdf

  errcheck:
    check-type-assertions: true
    check-blank: true

  unused:
    check-exported: true

  unparam:
    check-exported: true

  prealloc:
    for-loops: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
