on:
  push:
    branches:
      - '**'
      - '!main'
env:
  MUPDF_VERSION: 1.18.0

name: CI
jobs:
  quality:
    name: Quality
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Go cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ matrix.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-go-

      - name: Dependency linter
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod tidy
          git add .
          git diff --cached --exit-code

      - name: MuPDF cache
        id: cache
        uses: actions/cache@v2
        with:
          path: tmp/build/release
          key: ${{ matrix.os }}-mupdf-${{ env.MUPDF_VERSION }}

      - name: Checkout MuPDF code
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: ArtifexSoftware/mupdf
          ref: ${{ env.MUPDF_VERSION }}
          submodules: true
          path: tmp

      - name: Build MuPDF
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: tmp
        run: make tools

      - name: Build
        run: go build .

      - name: Test
        run: |
          export PATH="tmp/build/release:$PATH"
          go get github.com/mfridman/tparse
          go test -race -cover -covermode=atomic -json | tparse -all
          go test -race -bench .

      - name: Go golangci-lint
        if: matrix.os == 'ubuntu-latest'
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.40.1
          golangci-lint run -c misc/golangci/config.yml ./...
