on:
  push:
    branches:
      - "**"
      - "!main"

name: CI
jobs:
  quality:
    name: Quality
    timeout-minutes: 10
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - name: Go cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
            ~/Library/Caches/go-build
          key: ${{ matrix.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-go-

      - name: Install macOS dependencies
        if: matrix.alias == 'macos'
        run: |
          xcode-select --install || true
          brew install autoconf gcc

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          go install github.com/mfridman/tparse@v0.16.0
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.63.4

      - name: Dependency linter
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod tidy
          git add .
          git diff --cached --exit-code
          sudo apt-get update
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get install --no-install-recommends --yes ttf-mscorefonts-installer
          sudo rm -rf /var/lib/apt/lists/*
      - name: Build
        run: go build .

      - name: Test
        run: |
          go test -race -cover -covermode=atomic -json | tparse -all -smallscreen
          go test -race -bench .

      - name: Go golangci-lint
        if: matrix.os == 'ubuntu-latest'
        run: golangci-lint run -c misc/golangci/config.yml ./...
