on: push
name: CI
jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install mupdf
        run: SHALLOW_CLONE=true ./build

      - name: Test
        run: go test -v -race --timeout 1m
