on:
  push:
    branches:
      - '**'
      - '!main'

name: CI
jobs:
  quality:
    name: Quality
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Go cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
            ~/Library/Caches/go-build
          key: ${{ matrix.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-go-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          go install github.com/mfridman/tparse@v0.8.3
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1

      - name: Dependency linter
        if: matrix.os == 'ubuntu-latest'
        run: |
          go mod tidy
          git add .
          git diff --cached --exit-code

      - name: Build
        run: go build .

      - name: Test
        run: |
          go test -race -cover -covermode=atomic -json | tparse -all -dump -smallscreen
          go test -race -bench .

      - name: Go golangci-lint
        if: matrix.os == 'ubuntu-latest'
        run: golangci-lint run -c misc/golangci/config.yml ./...
