name: CI / snyk.io

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  snyk:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        target: [dependency-test, code-test]
        include:
          - target: dependency-test
            name: Snyk dependency scan
            cmd: snyk test --all-projects --exclude=misc --severity-threshold=high
            continue-on-error: true
          - target: code-test
            name: Snyk code analysis
            cmd: snyk code test --severity-threshold=high
            continue-on-error: false
    name: "${{ matrix.name }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"

      - name: Exec ${{ matrix.target }}
        env:
          SNYK_TOKEN: ${{ secrets.sn_x_pub }}
          SNYK_API: https://app.eu.snyk.io/api
        run: ${{ matrix.cmd }} --org=nitro-x
